### PR TITLE
Upgraded Vuetify

### PR DESCRIPTION
**Pull request by Sibin-Thomas**
Link to [issue](https://github.com/chamerling/gitlab-teams/issues/46)

### CODE REVIEW

**Comment by chamerling** [comment]
Migration from v1 to v2 is not so easy, the app does not start at all

**Comment by Sibin-Thomas** [comment]
I am looking into it.
based on this Release Notes
<https://vuetifyjs.com/en/getting-started/releases-and-migrations>

>

**Comment by cdterry87** [comment]
I actually upgraded a site from Vuetify 1.5 to 2.0 recently.  There are several breaking changes.  I attempted to upgrade this project and I have a somewhat working version of this project running on Vuetify 2 now.  I just need to finish renaming a bunch of the components, and I should be able to submit a pull request if this is still needed.

**Comment by Sibin-Thomas** [comment]
Yeah please do. I am not able to do it.

**Pull request closed without merging**
